import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Projects.module.css'
import Link from 'next/link'
import { Footer } from '../../compnents/footer'
import { Nav } from '../../compnents/nav'

export default function Projects({news}) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Projects</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Nav />
            <main className={styles.main}>
                <h1 className={styles.title}>
                    Projects
                </h1>
                <div id={styles.arrowDownFade}>
                    <img src="/downArrow.svg" class={styles.arrowDown}></img>
                </div>
            </main>
            <section className={styles.gridBody}>
                <div className={styles.gridcontainer}>
                    <>
                        {news.map((news) => {
                            return (
                                <Link href={news.id}><div className={styles.griditem}>{news.name}</div></Link>
                            )
                        })}
                    </>
                </div>
            </section>
            <Footer />
        </div>

        
    )
}


export async function getServerSideProps(){
    const res = await fetch(`http://suddsy.dev/api/projects`)
    const data = await res.json()
    console.log(data)
    return{
        props: {
            news: data,
        }
    }
}
//export async function getStaticProps(){
//    const res = await fetch(`http://192.168.1.221/projects`)
//    const data = await res.json()
//    console.log(data)
//    return{
//        props: {
//            news: data,
//        }
//    }
//}