import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/About.module.css'
import Link from 'next/link'
import { Footer } from '../compnents/footer'
import { Nav } from '../compnents/nav'

export default function About() {
    return (
        <div className={styles.container}>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Nav />
            <main className={styles.main}>
                <h1 className={styles.title}>
                    About
                </h1>
                <div id={styles.arrowDownFade}>
                    <img src="/downArrow.svg" className={styles.arrowDown}></img>
                </div>
            </main>
            <section className={styles.body} id={styles.main}>
                <h1>FAQ</h1>
                <div className={styles.ab}>
                    <div>
                        <h3>Q: What is this?</h3>
                        <p>This is a website to showcase my projects and skills!</p>
                        <h3>Q: What was this made with?</h3>
                        <p>This site was made using next-js</p>
                    </div>
                    <div>
                        <h3>Q: Contact?</h3>
                        <p>At this time contact me by email: **email**</p>
                        <h3>Q: What was this made with?</h3>
                        <p>This site was made using next-js</p>
                    </div>
                </div>
            </section>
            <Footer />
        </div>
    )
}