import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Nav } from "../compnents/nav"
import { Footer } from '../compnents/footer'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Nav />
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <strong className={styles.welcomeName}>My world</strong>
          </h1>
        </main>
        <Footer />
      </div>
    </div>
  )
}
