import Head from 'next/head'
import styles from '../styles/Local.module.css'
import { Nav } from "../compnents/nav"
import { Footer } from '../compnents/footer'
import Link from 'next/link'


export default function Local() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Local Sites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet" />
      </Head>
      <div>
        <Nav />
        <main className={styles.main}>
          <h1 className={styles.title}>
            Local Sites
          </h1>
        </main>
        <section className={styles.gridBody}>
            <div className={styles.gridcontainer}>
                <div className={styles.griditem}><Link href="http://pie.local:9000/" passHref><a>Portainer</a></Link></div>
                <div className={styles.griditem}><Link href="http://pie.local/" passHref><a>Main-Site</a></Link></div>
                <div className={styles.griditem}><Link href="http://pie.local:3002/" passHref><a>Dev-Site</a></Link></div>
                <div className={styles.griditem}><Link href="http://pie.local:7000/" passHref><a>Next Cloud</a></Link></div>
                <div className={styles.griditem}><Link href="http://pie.local:4000/" passHref><a>Firebase Chat</a></Link></div>
                <div className={styles.griditem}><Link href="http://pie.local:3000/" passHref><a>Json-Server</a></Link></div>
            </div>
        </section>
        <Footer />
      </div>
    </div>
  )
}
